baseURL = "https://www.dominicrodger.com/"
languageCode = "en-gb"
title = "Dominic Rodger"
theme = "hyde"

[params]
  description = " "
  themeColor = "theme-base-0e"

[permalinks]
posts = "/:year/:month/:day/:slug/"
